articles:
   path: /
   controller: App\Controller\ArticleController::index

article_add:
   path: /article/add/
   controller: App\Controller\ArticleController::addArticle

article:
   path: /article/{id}
   controller: App\Controller\ArticleController::article

article_edit:
   path: /article/edit/{id}
   controller: App\Controller\ArticleController::editArticle
   
api_login_check:
   path: /api/login_check