articles:
   path: /
   controller: App\Controller\ArticleController::index

article:
   path: /article/{id}
   controller: App\Controller\ArticleController::article
   
api_login_check:
   path: /api/login_check